name: Build
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-10.15, macos-12 ]
        java: [ 11 ]
        gradle: [ 6.9.4, 7.6.1 ]
        experimental: [ false ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      # Increases page file size on Windows, fixing JVM crashes such as "The paging file is too small for this operation
      # to complete"
      - uses: al-cheb/configure-pagefile-action@v1.3
        if: runner.os == 'Windows'
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        id: cache-mavenize
        with:
          path: |
            ~/.mavenize/eclipse_archive_cache/*.dmg
            ~/.mavenize/eclipse_archive_cache/*.zip
            ~/.mavenize/eclipse_archive_cache/*.tar.gz
          key: mavenize-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            mavenize-${{ runner.os }}-
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: buildAll --parallel --stacktrace
      # Print JVM crash/replay logs if the previous step failed.
      - id: print-jvm-crash-logs
        if: ${{ failure() }}
        run: cat hs_err_pid*.log; cat **/hs_err_pid*.log; cat replay_pid*.log; cat **/replay_pid*.log; true
        shell: bash {0}
